### ISSUE TITLE
  'ota' requires a 'platform' key but it was not specified.

### ISSUE THREAD

**Issue by ewoutdenheijer** [mhendriks/esphome-p1#12]
As of esphome 2024.6.0 the following error is raised when attempting ota using waterlezer.yaml:

  'ota' requires a 'platform' key but it was not specified.

**Comment by mhendriks** [comment]
I think it is because of this: https://esphome.io/changelog/2024.6.0.html#ota-platforms

Made some changes ... new version is available in Github.

**Comment by Robby-Swartenbroekx** [comment]
It's probably a "me" issue, but I still get those errors. What are the correct steps to fix this? This is the error I get when I try to install.
![image](https://github.com/mhendriks/esphome-p1/assets/16540999/28d7f136-18a6-42ca-9edc-f5d5c64694da)

**Comment by mhendriks** [comment]
Some time it takes 24h before the caches are cleared and the new configuration will be loaded

**Comment by Robby-Swartenbroekx** [comment]
I was afraid to update due to that error. but like you said, upgrade and it will work flawless afterwards. just needed that push to do the update because of this red text :-).
