### ISSUE TITLE
Package toolchain-riscv32-esp @ 8.4.0+2021r2-patch3 not found 

### ISSUE THREAD

**Issue by robgardien** [mhendriks/esphome-p1#2]
Ik krijg bij het updaten van ESPHome de volgende foutmelding:

Error: Could not find the package with 'espressif/toolchain-riscv32-esp @ 8.4.0+2021r2-patch3' requirements for your system 'linux_x86_64'

Ik gebruik de volgende YAML:

substitutions:
  name: p1-dongle-pro
packages:
  smartstuff.p1dongle_pro: github://mhendriks/esphome-p1/p1-dongle-pro.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

esp32:
  framework:
    version: 2.0.6

**Comment by mhendriks** [comment]
De config ziet er goed uit. 

Originele config is:

`esp32:
  board: esp32-c3-devkitm-1
  framework: 
    type: arduino
    version: 2.0.6
    platform_version: 4.4.0`

Helpt het als dit aangevuld wordt met alle gegevens zoals hierboven?

**Comment by deku-m** [comment]
Ik helaas ook het hetzelfde probleem

**Comment by mhendriks** [comment]
Gisteren met ESPHome versie 2023.5.1 succesvolle testen uitgevoerd. De specifieke platform settings zijn nu niet meer nodig :-)

Wellicht lost dit het probleem op. In de vorige variant  had specifieke versies nodig die wellicht problemen op sommige host platformen veroorzaakte.

esp32:
    board: esp32-c3-devkitm-1
 
De nieuwe versie is te vinden op deze github.

**Comment by deku-m** [comment]
Het werkt bij mij ook en meteen weer up to date. Thanks
