### ISSUE TITLE
Build error get_ip_address

### ISSUE THREAD

**Issue by FreddyX078** [mhendriks/esphome-p1#8]
Today, ESPHome got an update and on the DSMR I got this error:

INFO ESPHome 2024.3.0
INFO Reading configuration /config/esphome/dsmr-p1-pro.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing dsmr-p1-pro (board: esp32-c3-devkitm-1; framework: arduino; platform: platformio/espressif32@5.4.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32C3 160MHz, 320KB RAM, 4MB Flash
 - toolchain-riscv32-esp @ 8.4.0+2021r2-patch5
Dependency Graph
|-- AsyncTCP-esphome @ 2.1.3
|-- WiFi @ 2.0.0
|-- FS @ 2.0.0
|-- Update @ 2.0.0
|-- ESPAsyncWebServer-esphome @ 3.1.0
|-- ESPmDNS @ 2.0.0
|-- ArduinoJson @ 6.18.5
|-- Dsmr @ 0.8.0
|-- Crypto @ 0.4.0
Compiling .pioenvs/dsmr-p1-pro/src/esphome/components/network/util.cpp.o
Compiling .pioenvs/dsmr-p1-pro/src/esphome/components/text_sensor/text_sensor.cpp.o
Compiling .pioenvs/dsmr-p1-pro/src/esphome/components/uart/uart.cpp.o
Compiling .pioenvs/dsmr-p1-pro/src/esphome/components/uart/uart_component.cpp.o
src/esphome/components/network/util.cpp: In function 'esphome::network::IPAddresses esphome::network::get_ip_addresses()':
src/esphome/components/network/util.cpp:43:44: error: 'class esphome::ethernet::EthernetComponent' has no member named 'get_ip_addresses'; did you mean 'get_ip_address'?
     return ethernet::global_eth_component->get_ip_addresses();
                                            ^~~~~~~~~~~~~~~~
                                            get_ip_address
*** [.pioenvs/dsmr-p1-pro/src/esphome/components/network/util.cpp.o] Error 1
========================== [FAILED] Took 2.93 seconds ==========================

**Comment by FreddyX078** [comment]
Really strange.
Tried again with all original files and below is the full output.
Even on a fresh system I got this error.

Saw some differences between the dependency graph: 
You have DNSServer @ 2.0.0 and Improv @ 1.2.3.

`esphome run dsmr-original.yaml 
INFO ESPHome 2024.3.0
INFO Reading configuration dsmr-original.yaml...
INFO Generating C++ source...
INFO Core config or version changed, cleaning build files...
INFO Deleting .esphome/build/eth-dongle-pro/.pioenvs
INFO Deleting .esphome/build/eth-dongle-pro/.piolibdeps
INFO Compiling app...
Processing eth-dongle-pro (board: esp32-c3-devkitm-1; framework: arduino; platform: platformio/espressif32@5.4.0)
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Library Manager: Installing esphome/AsyncTCP-esphome @ 2.1.3
INFO Installing esphome/AsyncTCP-esphome @ 2.1.3
Unpacking  [####################################]  100%
Library Manager: AsyncTCP-esphome@2.1.3 has been installed!
INFO AsyncTCP-esphome@2.1.3 has been installed!
Library Manager: Installing esphome/ESPAsyncWebServer-esphome @ 3.1.0
INFO Installing esphome/ESPAsyncWebServer-esphome @ 3.1.0
Unpacking  [####################################]  100%
Library Manager: ESPAsyncWebServer-esphome@3.1.0 has been installed!
INFO ESPAsyncWebServer-esphome@3.1.0 has been installed!
Library Manager: Resolving dependencies...
INFO Resolving dependencies...
Library Manager: Installing bblanchon/ArduinoJson @ 6.18.5
INFO Installing bblanchon/ArduinoJson @ 6.18.5
Unpacking  [####################################]  100%
Library Manager: ArduinoJson@6.18.5 has been installed!
INFO ArduinoJson@6.18.5 has been installed!
Library Manager: Installing glmnet/Dsmr @ 0.8
INFO Installing glmnet/Dsmr @ 0.8
Unpacking  [####################################]  100%
Library Manager: Dsmr@0.8.0 has been installed!
INFO Dsmr@0.8.0 has been installed!
Library Manager: Installing rweather/Crypto @ 0.4.0
INFO Installing rweather/Crypto @ 0.4.0
Unpacking  [####################################]  100%
Library Manager: Crypto@0.4.0 has been installed!
INFO Crypto@0.4.0 has been installed!
HARDWARE: ESP32C3 160MHz, 320KB RAM, 4MB Flash
 - toolchain-riscv32-esp @ 8.4.0+2021r2-patch5
Dependency Graph
|-- AsyncTCP-esphome @ 2.1.3
|-- WiFi @ 2.0.0
|-- FS @ 2.0.0
|-- Update @ 2.0.0
|-- ESPAsyncWebServer-esphome @ 3.1.0
|-- ESPmDNS @ 2.0.0
|-- ArduinoJson @ 6.18.5
|-- Dsmr @ 0.8.0
|-- Crypto @ 0.4.0
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/api/api_connection.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/api/api_frame_helper.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/api/api_pb2.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/api/api_pb2_service.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/api/api_server.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/api/list_entities.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/api/proto.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/api/subscribe_state.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/api/user_services.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/button/button.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/dashboard_import/dashboard_import.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/dsmr/dsmr.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/esp32/core.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/esp32/gpio.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/esp32/preferences.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/ethernet/esp_eth_phy_jl1101.c.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/ethernet/ethernet_component.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/factory_reset/button/factory_reset_button.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/json/json_util.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/logger/logger.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/logger/logger_esp32.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/logger/logger_esp8266.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/logger/logger_host.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/logger/logger_libretiny.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/logger/logger_rp2040.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/md5/md5.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/mdns/mdns_component.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/mdns/mdns_esp32.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/mdns/mdns_esp8266.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/mdns/mdns_host.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/mdns/mdns_libretiny.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/mdns/mdns_rp2040.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/network/util.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/ota/ota_backend_arduino_esp32.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/ota/ota_backend_arduino_esp8266.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/ota/ota_backend_arduino_libretiny.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/ota/ota_backend_arduino_rp2040.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/ota/ota_backend_esp_idf.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/ota/ota_component.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/restart/button/restart_button.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/sensor/automation.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/sensor/filter.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/sensor/sensor.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/socket/bsd_sockets_impl.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/socket/lwip_raw_tcp_impl.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/socket/lwip_sockets_impl.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/socket/socket.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/text_sensor/filter.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/text_sensor/text_sensor.cpp.o
src/esphome/components/network/util.cpp: In function 'esphome::network::IPAddresses esphome::network::get_ip_addresses()':
src/esphome/components/network/util.cpp:43:44: error: 'class esphome::ethernet::EthernetComponent' has no member named 'get_ip_addresses'; did you mean 'get_ip_address'?
     return ethernet::global_eth_component->get_ip_addresses();
                                            ^~~~~~~~~~~~~~~~
                                            get_ip_address
*** [.pioenvs/eth-dongle-pro/src/esphome/components/network/util.cpp.o] Error 1
====================================================================================== [FAILED] Took 7.11 seconds ======================================================================================`

**Comment by mhendriks** [comment]
One difference is I'm using p1-dongle-pro config and in the last error output I see ethernet dongle pro ... I will check it again.

It can be reproduced:

 % esphome run eth-dongle-pro.yaml 
INFO ESPHome 2024.3.0
INFO Reading configuration eth-dongle-pro.yaml...
INFO Updating https://github.com/mhendriks/esphome-p1.git@main
INFO Generating C++ source...
INFO Compiling app...
Processing eth-dongle-pro (board: esp32-c3-devkitm-1; framework: arduino; platform: platformio/espressif32@5.4.0)
-------------------------------------------------------------------------------------------------------------------------------
Removing unused dependencies...
Library Manager: Removing AsyncTCP-esphome @ 2.0.1
INFO Removing AsyncTCP-esphome @ 2.0.1
Library Manager: AsyncTCP-esphome@2.0.1 has been removed!
INFO AsyncTCP-esphome@2.0.1 has been removed!
Library Manager: Installing esphome/AsyncTCP-esphome @ 2.1.3
INFO Installing esphome/AsyncTCP-esphome @ 2.1.3
Unpacking  [####################################]  100%
Library Manager: AsyncTCP-esphome@2.1.3 has been installed!
INFO AsyncTCP-esphome@2.1.3 has been installed!
HARDWARE: ESP32C3 160MHz, 320KB RAM, 4MB Flash
 - toolchain-riscv32-esp @ 8.4.0+2021r2-patch5
Dependency Graph
|-- AsyncTCP-esphome @ 2.1.3
|-- WiFi @ 2.0.0
|-- FS @ 2.0.0
|-- Update @ 2.0.0
|-- ESPAsyncWebServer-esphome @ 3.1.0
|-- ESPmDNS @ 2.0.0
|-- ArduinoJson @ 6.18.5
|-- Dsmr @ 0.8.0
|-- Crypto @ 0.4.0
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/api/api_connection.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/api/api_frame_helper.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/api/api_pb2.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/api/api_pb2_service.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/api/api_server.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/api/list_entities.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/api/proto.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/api/subscribe_state.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/api/user_services.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/button/button.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/dashboard_import/dashboard_import.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/dsmr/dsmr.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/esp32/core.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/esp32/gpio.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/esp32/preferences.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/ethernet/esp_eth_phy_jl1101.c.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/ethernet/ethernet_component.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/factory_reset/button/factory_reset_button.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/json/json_util.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/logger/logger.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/logger/logger_esp32.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/logger/logger_esp8266.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/logger/logger_host.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/logger/logger_libretiny.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/logger/logger_rp2040.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/md5/md5.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/mdns/mdns_component.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/mdns/mdns_esp32.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/mdns/mdns_esp8266.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/mdns/mdns_host.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/mdns/mdns_libretiny.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/mdns/mdns_rp2040.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/network/util.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/ota/ota_backend_arduino_esp32.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/ota/ota_backend_arduino_esp8266.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/ota/ota_backend_arduino_libretiny.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/ota/ota_backend_arduino_rp2040.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/ota/ota_backend_esp_idf.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/ota/ota_component.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/restart/button/restart_button.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/sensor/automation.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/sensor/filter.cpp.o
Compiling .pioenvs/eth-dongle-pro/src/esphome/components/sensor/sensor.cpp.o
src/esphome/components/network/util.cpp: In function 'esphome::network::IPAddresses esphome::network::get_ip_addresses()':
src/esphome/components/network/util.cpp:43:44: error: 'class esphome::ethernet::EthernetComponent' has no member named 'get_ip_addresses'; did you mean 'get_ip_address'?
     return ethernet::global_eth_component->get_ip_addresses();
                                            ^~~~~~~~~~~~~~~~
                                            get_ip_address
*** [.pioenvs/eth-dongle-pro/src/esphome/components/network/util.cpp.o] Error 1
================================================= [FAILED] Took 6.99 seconds

**Comment by mhendriks** [comment]
I will check for a solution ...

**Comment by mhendriks** [comment]
<img width="699" alt="Screenshot 2024-03-22 at 10 22 45" src="https://github.com/mhendriks/esphome-p1/assets/4169609/9eb89ae9-0a0c-4bb8-a7a9-9452e40bbe89">

**Comment by mhendriks** [comment]
external ethernet component for spi ethernet support isn't needed. The 24.3.0 version contains ws5500 spi support. 

comment out some parts of the config will do the trick ;-)

```
# external_components:
# #   - source: github://mhendriks/esphome-p1@main
#   - source: my_components
#     components: [ ethernet ]

          
ethernet:
  type: W5500
  cs_pin: 10
  clk_pin: 4
  mosi_pin: 6
  miso_pin: 5
  interrupt_pin: 1
#   clock_speed: 25
#   manual_ip:
#     static_ip: 192.168.2.123
#     gateway: 192.168.2.1
#     subnet: 255.255.255.0
```

 I didn't check if the dongle is function properly after changes... to be continued

**Comment by FreddyX078** [comment]
Yes, you're right, that did the trick!
Thanks!
