### ISSUE TITLE
Cant adopt new s0 dongle - unsupported ota version 2

### ISSUE THREAD

**Issue by Nijhuis** [mhendriks/esphome-p1#9]
When trying to adopt a new S0 Dongle, i get the following error.

Linking .pioenvs/s0-dongle/firmware.elf
RAM:   [=====     ]  49.2% (used 40268 bytes from 81920 bytes)
Flash: [=====     ]  50.6% (used 528221 bytes from 1044464 bytes)
Building .pioenvs/s0-dongle/firmware.bin
esp8266_copy_factory_bin([".pioenvs/s0-dongle/firmware.bin"], [".pioenvs/s0-dongle/firmware.elf"])
========================= [SUCCESS] Took 58.79 seconds =========================
INFO Successfully compiled program.
INFO Resolving IP address of s0-dongle.local
INFO  -> 192.168.10.127
INFO Uploading /config/.esphome/build/s0-dongle/.pioenvs/s0-dongle/firmware.bin (532368 bytes)
ERROR Unsupported OTA version 2

**Comment by mhendriks** [comment]
strange ... is it possible to upload the bin via the web interface?

**Comment by Nijhuis** [comment]
I am not sure what file I need to upload. You mean via the OTA upload form?

**Comment by mhendriks** [comment]
You should upload this file: /config/.esphome/build/s0-dongle/.pioenvs/s0-dongle/firmware.bin via de s0-dongle web page upload fuction. This function is located on the bottom of this page.

**Comment by Nijhuis** [comment]
Yes found it, edited my previous comment. 👍
